apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: prod
  name: postgres-volumes
  labels:
    type: longhorn
spec:
  storageClassName: longhorn
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io
    volumeHandle: postgres-volumes