apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  # Pas de storageClassName - utilise le défaut de Kind